import type { Metadata } from "next";
import Link from "next/link";
import { media } from "../../content/media";
import { MediaImage } from "../../components/MediaImage";
import { Reveal } from "../../components/Reveal";
import { VisualCard } from "../../components/VisualCard";
import { OpportunityCarousel } from "../../components/OpportunityCarousel";
import { Icon } from "../../components/Icon";

export const metadata: Metadata = { title: "Global Opportunities", description: "A Wyoming foundation and a global perspective: explore the people, places and business themes that shape opportunity.", alternates: { canonical: "https://dwpwyomingllc.com/opportunities/" }, openGraph: { title: "Global Opportunities | DWP Wyoming LLC", description: "A wider view of business, rooted in Wyoming.", url: "https://dwpwyomingllc.com/opportunities/", images: [{ url: media.opportunitiesDubai }] }, twitter: { card: "summary_large_image", title: "Global Opportunities | DWP Wyoming LLC", description: "A wider view of business, rooted in Wyoming.", images: [media.opportunitiesDubai] } };

export default function Opportunities() {
  return <main id="main-content">
    <section className="page-hero opportunities-hero"><div className="page-hero-visual"><MediaImage src={media.opportunitiesDubai} alt="Dubai skyline at sunset reflected across the water" className="page-hero-image" priority/></div><div className="page-hero-shade"/><div className="container page-hero-content"><span className="eyebrow page-enter">DWP WYOMING LLC / GLOBAL OPPORTUNITIES</span><h1 className="page-enter">From Wyoming <em>to the world.</em></h1><p className="page-enter">Opportunity is not a place on a map. It is a meeting point between informed people, thoughtful ideas and the right context.</p><div className="page-hero-actions page-enter"><a href="#wyoming-world" className="button button-gold">Explore the Perspective <Icon name="arrow" size={18}/></a></div></div><div className="page-hero-index container"><span>GLOBAL VIEW / LOCAL FOUNDATION</span><span>DWP WYOMING LLC</span></div></section>
    <section className="section-pad" id="wyoming-world"><div className="container opportunities-intro"><Reveal><span className="eyebrow dark-eyebrow">01 / TWO VANTAGE POINTS</span><h2>A firm foundation. <em>An open horizon.</em></h2></Reveal><Reveal delay={120}><p>Wyoming represents the foundation of DWP’s identity. Global business centers represent a wider field of ideas and relationships. Our perspective connects the two without claiming a physical presence or transaction in every location.</p></Reveal></div><div className="world-split container"><div className="split-pane"><MediaImage src={media.opportunitiesWyoming} alt="Grand Teton mountains in a Wyoming landscape" className="split-image"/><span>WYOMING / FOUNDATION</span></div><div className="split-divider" aria-hidden="true"><span/></div><div className="split-pane"><div className="split-art" aria-hidden="true"><Icon name="globe" size={120}/><div className="split-rings"/></div><span>THE WORLD / PERSPECTIVE</span></div></div></section>
    <section className="section-pad section-muted"><div className="container"><Reveal><span className="eyebrow dark-eyebrow">02 / WHAT CONNECTS US</span><div className="section-head"><h2>Connection is <em>a deliberate practice.</em></h2><p>Three principles for exploring unfamiliar environments with care.</p></div></Reveal><div className="visual-card-grid"><VisualCard card={{ title: "Listen locally", body: "Each market has its own rules, people and lived realities. Begin by understanding them.", icon: "globe" }} index={0}/><VisualCard card={{ title: "Understand the structure", body: "A promising idea still needs clear ownership, responsibilities and boundaries.", icon: "plan" }} index={1}/><VisualCard card={{ title: "Move thoughtfully", body: "Progress is more durable when assumptions are tested before commitments are made.", icon: "growth" }} index={2}/></div></div></section>
    <OpportunityCarousel/>
    <section className="section-pad opportunities-close"><div className="container editorial-end-grid"><Reveal><span className="eyebrow dark-eyebrow">THE NEXT STEP</span><h2>There is more to explore.</h2></Reveal><Reveal delay={100}><p>Start with your question, your context and the type of connection you are looking for. A constructive first conversation begins there.</p><Link href="/contact" className="text-link">Contact DWP <Icon name="arrow" size={19}/></Link></Reveal></div></section>
  </main>;
}
